# config context path to "/" by setting an empty string
server:
  contextPath:

# jackson
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
#jwt
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
#logging
logging:
  level: INFO
#  path: ${user.home}/rest-security-demo/log
